future: true
permalink: /:title/
url: http://guoxiongfeng.github.io
name: Guoxf
author: Guoxf
qq: 530416041
email: Secret

duoshuo: yourname
beian: None
cnzz: None
weibo: None
github: guoxiongfeng
about: "这里是 guoxiongfeng 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
